<?php

namespace BikeBundle\Repository;

/**
 * CarteFidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteFidRepository extends \Doctrine\ORM\EntityRepository
{
}
