<?php

namespace BikeBundle\Repository;

/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
}
