evenement_index:
    path:     /
    defaults: { _controller: "BikeBundle:Evenement:index" }
    methods:  GET

evenement_show:
    path:     /{id}/show
    defaults: { _controller: "BikeBundle:Evenement:show" }
    methods:  GET

evenement_new:
    path:     /new
    defaults: { _controller: "BikeBundle:Evenement:new" }
    methods:  [GET, POST]

evenement_edit:
    path:     /{id}/edit
    defaults: { _controller: "BikeBundle:Evenement:edit" }
    methods:  [GET, POST]

evenement_delete:
    path:     /{id}/delete
    defaults: { _controller: "BikeBundle:Evenement:delete" }
    methods:  DELETE

evenement_calendrier:
    path:     /calendrier
    defaults: { _controller: "BikeBundle:Evenement:calendrier" }
    methods:  GET

evenement_indexf:
    path:     /F
    defaults: { _controller: "BikeBundle:Evenement:indexf" }

evenement_mail:
    path:     /mail/{event}
    defaults: { _controller: "BikeBundle:Evenement:mail" }

