<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBtb7ppi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBtb7ppi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBtb7ppi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBtb7ppi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBtb7ppi\appDevDebugProjectContainer([
    'container.build_hash' => 'Btb7ppi',
    'container.build_id' => 'bedfe0a2',
    'container.build_time' => 1582078495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBtb7ppi');
