<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2fju7kv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2fju7kv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2fju7kv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2fju7kv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2fju7kv\appDevDebugProjectContainer([
    'container.build_hash' => '2fju7kv',
    'container.build_id' => 'f0b8a84f',
    'container.build_time' => 1581197163,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2fju7kv');
