<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container53xbw6e\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container53xbw6e/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container53xbw6e.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container53xbw6e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container53xbw6e\appDevDebugProjectContainer([
    'container.build_hash' => '53xbw6e',
    'container.build_id' => 'bf23d182',
    'container.build_time' => 1581420808,
], __DIR__.\DIRECTORY_SEPARATOR.'Container53xbw6e');
